# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: VieWalker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.10'
      - name: Update Homebrew
        run: brew update
      - name: Install SwiftLint and SwiftFormat
        run: |
          brew install swiftlint
          brew install swiftformat
      - name: SwiftFormat
        run: swiftformat . --lint
      - name: SwiftLint
        run: swiftlint lint --strict
      - name: Build and Test
        run: |
          xcodebuild \
           -workspace VN-Walker.xcworkspace \
           -scheme VN-Walker \
           -sdk iphonesimulator \
           -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0.1' 
